import { useState } from "react";
import { TABLE_STYLE_PRESETS, type TableStylePreset, type TableStyleOptions } from "@open-office/spreadsheet-ui";
export function SpreadsheetTableStyles({ onPick, onClear, ribbon, currentOptions, currentPreset, disabled }: { ribbon?: boolean; currentOptions?: TableStyleOptions; currentPreset?: TableStylePreset; disabled?: boolean; onPick: (preset: TableStylePreset, options: TableStyleOptions) => void; onClear: () => void }) {
  const [localOptions, setOptions] = useState<TableStyleOptions>({ headerRow: true, headerColumn: false, outline: false, filter: false, pattern: "rows" });
  const options = currentOptions ?? localOptions;
  return <div className={`ssr__table-styles${ribbon ? " ssr__table-styles--ribbon" : ""}`} aria-label="表格样式">
    <div className="ssr__table-options">{([["headerRow", "标题行"], ["headerColumn", "标题列"], ["outline", "表格外框线"], ["filter", "筛选按钮"]] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={options[key]} disabled={disabled} onChange={event => { const next = { ...options, [key]: event.target.checked }; if (ribbon && currentPreset) onPick(currentPreset, next); else setOptions(next); }} />{label}</label>)}</div>
    {([["rows", "隔行填充色"], ["borders", "隔行边框线"], ["columns", "隔列填充色"]] as const).filter(([pattern]) => !ribbon || options.pattern === pattern).map(([pattern, label]) => <section key={pattern}><h3>{label}</h3><div className="ssr__table-gallery">{TABLE_STYLE_PRESETS.map(preset => <button type="button" role={ribbon ? "button" : "menuitem"} aria-pressed={ribbon ? currentPreset === preset.id : undefined} disabled={disabled} key={preset.id} title={`${preset.label} · ${label}`} aria-label={pattern === "rows" ? preset.label : `${preset.label} · ${label}`} onClick={() => onPick(preset.id, { ...options, pattern })}><span className="ssr__table-preview" aria-hidden="true">{Array.from({ length: 20 }, (_, index) => { const row = Math.floor(index / 4), column = index % 4; const header = (options.headerRow && row === 0) || (options.headerColumn && column === 0); return <i key={index} style={{ background: header ? preset.header : pattern === "rows" && row % 2 === 1 || pattern === "columns" && column % 2 === 1 ? preset.stripe : "#fff", borderBottom: pattern === "borders" && row % 2 === 1 ? `1px solid ${preset.header}` : undefined }} />; })}</span></button>)}</div></section>)}
    {ribbon && <label className="ssr__table-pattern">条纹样式<select aria-label="条纹样式" disabled={disabled} value={options.pattern} onChange={event => { if (currentPreset) onPick(currentPreset, { ...options, pattern: event.target.value as TableStyleOptions["pattern"] }); }}><option value="rows">隔行填充色</option><option value="borders">隔行边框线</option><option value="columns">隔列填充色</option></select></label>}
    <div className="ssr__table-footer"><button disabled={disabled} type="button" onClick={onClear}>{ribbon ? "清除表格样式" : "清除选区格式"}</button>{!ribbon && <span>应用于当前选区</span>}</div>
  </div>;
}
